language: node_js
node_js:
- v0.12.6
before_install:
  - "npm install -g npm@latest"
before_script:
- npm install -g mocha
after_success:
- npm run coverage-text
deploy:
  provider: npm
  api_key:
    secure: VeK3IB1GCir3wOPdehkHLsr2UtH8ZQwDSzE/j+7s9Myxd2o2YbJA2dFODobywyvulVNlejDNUGnn49QW7QIfthXDrA2iMuBVUtLsbKws27Y361Ng7NR0HwDueMIjTc5qoHX51ilt853C/ZPUNN1DIFBDavtx8qEAC+fR3Vm+2ew=
